# Rolling window for arrays in NumPy

[Self-link](https://colab.research.google.com/drive/1WPwxovVxXi9YBrQVUavaSJMt7I0rwlNh)

**Disclaimer**: *author could be wrong!* If you see the error, please, write me at [foobar167@gmail.com](mailto:foobar167@gmail.com?subject=%20Rolling%20window%20error).

It is possible to implement a rolling window for NumPy arrays and images *without explicit cycles* in Python. As a result the speed of a such rolling window will be comparable to the speed of **C** programming language. Because NumPy library is implemented in the **C** programming language. It is in several thousand times faster than explicit Python `for` cycles.

  00. [Introduction](#introduction)
  00. [Rolling 1D window for ND array in Numpy](#1d)
  00. [Rolling 2D window for ND array in Numpy](#2d)
  00. [Rolling 3D window for ND array in Numpy](#3d)
  00. [Rolling MD window for ND array, where M ≤ N](#md)
  00. [Rolling MD window for ND array for any M and N](#md-extended)

## <a name="introduction">Introduction</a>
This article is an extension of [my answer](https://stackoverflow.com/a/46237736/7550928) on the StackOverflow. My first experiments with the rolling window are [here](https://github.com/foobar167/junkyard/blob/master/rolling_window.py) and [here](https://github.com/foobar167/junkyard/blob/master/rolling_window_advanced.py).

**Practical implementation** of the rolling 2D window for 2D array in NumPy is in the `roll` function of the [`logic_tools.py`](https://github.com/foobar167/junkyard/blob/master/manual_image_annotation1/polygon/logic_tools.py) file of the [Manual image annotation with polygons](https://github.com/foobar167/junkyard/tree/master/manual_image_annotation1) project.

Basics rolling window technique for 1D array is already explained [here](https://stackoverflow.com/a/7100681/7550928), [here](https://rigtorp.se/2011/01/01/rolling-statistics-numpy.html) and [here](https://stackoverflow.com/questions/6811183/rolling-window-for-1d-arrays-in-numpy).

To understand the topic, you must know what [strides](https://stackoverflow.com/a/53099870/7550928) are.

In [0]:
# Import necessary libraries
import numpy as np

## <a name="1d" />1. Rolling 1D window for ND array in Numpy

In [0]:
# Rolling 1D window for ND array
def roll(a,    # ND array
         b,    # rolling 1D window array
         dx):  # step size (horizontal)
    shape = a.shape[:-1] + (int((a.shape[-1] - b.shape[-1]) / dx) + 1,) + b.shape
    strides = a.strides[:-1] + (a.strides[-1] * dx,) + a.strides[-1:]
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

There are 2 major things for newly created array: **shape** and **strides**. Shape of the new array is created via shape of the input ND array and shape of the rolling 1D window. While strides are created only via strides of the input ND array (without rolling window).

Step size of the rolling window **dx** is equal to 1, 2, 3, etc. and always horizontal for 1D rolling window.

*Shape* consists from 3 terms:
  * `a.shape[:-1]` is the array shape remainder for ND arrays where `N > 1`. For `N == 1` array remainder will be equal to empty tuple `t == ()`, so it is not necessary for `N == 1`.
  * `(int((a.shape[-1] - b.shape[-1]) / dx) + 1,)` is the number of steps of the rolling 1D window over last dimension of the ND array.
  * `b.shape` is the shape of the rolling window.

*Strides* also consist from 3 terms:
  * `a.strides[:-1]` is the array strides remainder for ND array where `N > 1`. For `N == 1` array remainder will be equal to empty tuple `t == ()`, so it is not necessary for `N == 1`.
  * `(a.strides[-1] * dx,)` is the number of bytes between steps of the rolling window. For example, `int` array has 4 bytes stride between neighbour elements, so for step `dx == 2` it should be `4 * 2 = 8` bytes between steps of the rolling window.
  * `(a.strides[-1],)` is the stride between neighbour elements of the input ND array. For example, for `int` it should be equal 4 bytes or tuple `(4,)`.

  Function [`numpy.lib.stride_tricks.as_strided`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.lib.stride_tricks.as_strided.html) creates a view into the array with the given shape and strides.

In [4]:
# Tests
def show_results(a, b, dx):
    axis = a.ndim  # number of dimensions
    bool_array = np.all(roll(a, b, dx) == b, axis=axis)
    counts = np.count_nonzero(bool_array)
    coords = np.transpose(np.nonzero(bool_array)) * [1, dx]
    print("Found {counts} elements with coordinates:\n{coords}".format(
        counts=counts, coords=coords))

a = np.array([[ 0,  1,  2,  3,  4,  5],
              [ 7,  8,  7,  8, 10, 11],
              [13, 14, 13, 14,  7,  8],
              [19, 20, 19, 20, 13, 14],
              [24, 25, 26, 27, 19, 20]], dtype=np.int)

# Should find: 3 elements if dx == 1 or 2
#              1 element  if dx == 3
#              2 elements if dx == 4
b1 = np.array([7, 8], dtype=np.int)
show_results(a, b1, 1)
show_results(a, b1, 2)
show_results(a, b1, 3)
show_results(a, b1, 4)

# Should find: 1 element  if dx == 1
#              0 elements if dx == 2
b2 = np.array([8, 7], dtype=np.int)
print("----------")
show_results(a, b2, 1)
show_results(a, b2, 2)

Found 3 elements with coordinates:
[[1 0]
 [1 2]
 [2 4]]
Found 3 elements with coordinates:
[[1 0]
 [1 2]
 [2 4]]
Found 1 elements with coordinates:
[[1 0]]
Found 2 elements with coordinates:
[[1 0]
 [2 4]]
----------
Found 1 elements with coordinates:
[[1 1]]
Found 0 elements with coordinates:
[]


## <a name="2d" />2. Rolling 2D window for ND array in Numpy

In [0]:
# Rolling 2D window for ND array
def roll(a,    # ND array
         b,    # rolling 2D window array
         dx,   # horizontal step, number of columns
         dy):  # vertical step, number of rows
    shape = a.shape[:-2] + \
            (int((a.shape[0] - b.shape[0]) / dy) + 1,) + \
            (int((a.shape[1] - b.shape[1]) / dx) + 1,) + \
            b.shape  # sausage-like shape with 2D cross-section
    strides = a.strides[:-2] + \
              (a.strides[0] * dy,) + \
              (a.strides[1] * dx,) + \
              a.strides[-2:]
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

There are also shape and strides like in [section one](#1d), but for rolling 2D window.

*Shape* consists from 4 terms: 3 terms like in [section one](#1d) and the 4th term is the number of vertical steps `(int((a.shape[0] - b.shape[0]) / dy) + 1,)` of the rolling 2D window.

*Strides* are also similar to [section one](#1d), but with additional stride `(a.strides[0] * dy,)` for vertical step of the rolling 2D window.

In [11]:
# Tests
def show_results(a, b, dx, dy):
    axis = a.ndim  # number of dimensions
    bool_array = np.all(
                   np.all(roll(a, b, dx, dy) == b, axis=axis),
                 axis=axis)  # np.all over 2 dimensions of the rolling 2D window
    counts = np.count_nonzero(bool_array)
    coords = np.transpose(np.nonzero(bool_array)) * [dy, dx]
    print("Found {counts} elements with coordinates:\n{coords}".format(
        counts=counts, coords=coords))

a = np.array([[ 0,  1,  2,  3,  4,  5],
              [ 7,  8,  7,  8, 10, 11],
              [13, 14, 13, 14,  7,  8],
              [19, 20, 19, 20, 13, 14],
              [24, 25, 26, 27, 19, 20]], dtype=np.int)

# Should find: 3 elements if dx == 1 or 2
#              1 element  if dx == 3
#              2 elements if dx == 4
b1 = np.array([[ 7,  8],
               [13, 14]], dtype=np.int)
show_results(a, b1, 1, 1)
show_results(a, b1, 2, 1)
show_results(a, b1, 3, 1)
show_results(a, b1, 4, 1)

# Should find: 1 element  if dx == 1
#              0 elements if dx == 2
b2 = np.array([[ 8,  7],
               [14, 13]], dtype=np.int)
print("----------")
show_results(a, b2, 1, 1)
show_results(a, b2, 2, 1)

Found 3 elements with coordinates:
[[1 0]
 [1 2]
 [2 4]]
Found 3 elements with coordinates:
[[1 0]
 [1 2]
 [2 4]]
Found 1 elements with coordinates:
[[1 0]]
Found 2 elements with coordinates:
[[1 0]
 [2 4]]
----------
Found 1 elements with coordinates:
[[1 1]]
Found 0 elements with coordinates:
[]


## <a name="3d" />3. Rolling 3D window for ND array in Numpy

In [0]:
# Rolling 3D window for ND array


In [0]:
# Tests


## <a name="md" />4. Rolling MD window for ND array, where M ≤ N

In [0]:
# Rolling MD window for ND array


In [0]:
# Tests


## <a name="md-extended" />5. Rolling MD window for ND array for any M and N
Can we roll MD window for ND arrays, where M > N? Actually, we can, but only part of the rolling window which **intersects** with ND array.

In [0]:
# Rolling MD window for ND array


In [0]:
# Tests
